require_relative('../models/book')
require_relative('../models/author')
require_relative('../models/stock')
require_relative('./sql_runner')
require('pry-byebug')

author1 = Author.new({'name' => 'L.M. Montgomery'})
author1.save()
author2 = Author.new({'name' => 'J.K Rowling'})
author2.save()

book1 = Book.new({'title' => 'Anne of Green Gables', 'author_id' => author1.id, 'buy_price' => 3, 'sell_price' => 5})
book1.save()
book2 = Book.new({'title' => 'Anne of Avonlea', 'author_id' => author1.id, 'buy_price' => 2, 'sell_price' => 4})
book2.save()
book3 = Book.new({'title' => 'Harry Potter and the Philosopher''s Stone', 'author_id' => author2.id, 'buy_price' => 10, 'sell_price' => 15})
book3.save()
book4 = Book.new({'title' => 'Harry Potter and the Deathly Hallows', 'author_id' => author2.id,'buy_price' => 10, 'sell_price' => 17})
book4.save()

stock1 = Stock.new({'book_id'=> book1.id, 'author_id' => book1.author.id, 'quantity' => 15})
stock1.save()
stock2 = Stock.new({'book_id'=> book2.id, 'author_id' => book2.author.id, 'quantity' => 9})
stock2.save()
stock3 = Stock.new({'book_id'=> book3.id, 'author_id' => book3.author.id, 'quantity' => 2})
stock3.save()
