require_relative('../models/book')
require_relative('../models/author')
require_relative('../models/stock')
require_relative('./sql_runner')
require('pry-byebug')

author1 = Author.new({'name' => 'L.M. Montgomery'})
author1.save()
author2 = Author.new({'name' => 'J.K Rowling'})
author2.save()
author3 = Author.new({'name' => 'Philip Pullman'})
author3.save()
author4 = Author.new({'name' => 'Gail Carson Levine'})
author4.save()
author5 = Author.new({'name' => 'Tina Fey'})
author5.save()

book1 = Book.new({'title' => 'Anne of Green Gables', 'author_id' => author1.id, 'buy_price' => 3.00, 'sell_price' => 5.99})
book1.save()
book2 = Book.new({'title' => 'Anne of Avonlea', 'author_id' => author1.id, 'buy_price' => 2.50, 'sell_price' => 4.00})
book2.save()
book3 = Book.new({'title' => 'Harry Potter and the Philosopher''s Stone', 'author_id' => author2.id, 'buy_price' => 10.00, 'sell_price' => 15.00})
book3.save()
book4 = Book.new({'title' => 'Harry Potter and the Deathly Hallows', 'author_id' => author2.id,'buy_price' => 10.00, 'sell_price' => 17.99})
book4.save()
book5 = Book.new({'title' => 'The Golden Compass', 'author_id' => author3.id,'buy_price' => 9.00, 'sell_price' => 11.99})
book5.save()
book6 = Book.new({'title' => 'Ella Enchanted', 'author_id' => author4.id,'buy_price' => 7.50, 'sell_price' => 11.99})
book6.save()
book7 = Book.new({'title' => 'Bossypants', 'author_id' => author5.id,'buy_price' => 7.25, 'sell_price' => 10.99})
book7.save()

stock1 = Stock.new({'book_id'=> book1.id, 'author_id' => book1.author.id, 'quantity' => 15})
stock1.save()
stock2 = Stock.new({'book_id'=> book2.id, 'author_id' => book2.author.id, 'quantity' => 9})
stock2.save()
stock3 = Stock.new({'book_id'=> book3.id, 'author_id' => book3.author.id, 'quantity' => 2})
stock3.save()
stock4 = Stock.new({'book_id'=> book5.id, 'author_id' => book5.author.id, 'quantity' => 3})
stock4.save()
stock4 = Stock.new({'book_id'=> book6.id, 'author_id' => book6.author.id, 'quantity' => 10})
stock4.save()
stock5 = Stock.new({'book_id'=> book7.id, 'author_id' => book7.author.id, 'quantity' => 7})
stock5.save()


